services:
  postgres:
    environment:
      POSTGRES_DB: comics_db
      POSTGRES_PASSWORD: comics_password
      POSTGRES_USER: comics_user
    image: postgres:${POSTGRES_VERSION:-alpine}
    ports:
      - mode: bridge
        protocol: tcp
        published: "5432"
        target: "5432"
    volumes:
      - source: postgres_data
        target: /var/lib/postgresql/data
        type: volume

volumes:
  postgres_data:
